#!/bin/sh
# Copyright 2026 edcsnt. All rights reserved.

config='
01-01
01-25
04-21
05-01
07-09
09-07
10-12
11-02
11-15
11-20
12-24
12-25
12-31
2026-02-17
2026-02-18
2026-04-03
2026-06-04
'

echo() { printf %s\\n "$*"; }
log() { echo "$@"; } >&2
die() { log "$@"; exit 2; }

[ $# -eq 1 ] || die usage: "$0" file

y=$(date +%Y)
t=$(date +%Y-%m-%d)
nl='
'

skip=
for d in $config
do
	case $d in
	[0-9][0-9]-[0-9][0-9]) skip=$skip$nl$y-$d ;;
	                    *) skip=$skip$nl$d    ;;
	esac
done

case $skip in
*$t*) log "$t" is a skip day; exit 1 ;;
esac

log clocking in/out
read -r f <"$1"
curl -d UserName="${f%%:*}" --data-urlencode Password="${f#*:}" \
	https://www.dimepkairos.com.br/Dimep/Account/Marcacao
