.\" Copyright 2026 edcsnt. All rights reserved.
.Dd January 8, 2026
.Dt KROS 1
.Os
.Sh NAME
.Nm kros
.Nd clock in and out of Kairos
.Sh SYNOPSIS
.Nm
.Op Fl f
.Ar file
.Sh DESCRIPTION
.Nm
is an
.St -p1003.1-2008 Ns \(enconformant
shell script that clocks a user in and out of the Kairos electronic
timekeeping system from DIMEP.
.Pp
Skip days are configured in-script: Except when
.Fl f
is specified,
.Sy %Y-%m-%d
.Pq see Xr strftime 3
and
.Sy %m-%d
dates in the
.Em config
variable are skipped.
.Sy %m-%d
dates recur annually.
.Pp
A warning about
.Xr systemd.timer 5 :
If the calendar timer elapses while the system is sleeping, service
activation will unconditionally happen upon system resumption,
potentially resulting in an incorrect time marking.
.Pp
.Nm
is pronounced
.Dq cross .
The following option is supported:
.Bl -tag -width Ds
.It Fl f
Forced mode. Ignore the contents of the
.Em config
variable and always clock in/out.
.El
.Sh OPERANDS
The following operand is supported:
.Bl -tag -width Ds
.It Ar file
Credentials file. The first line must contain the user's email address
and password separated by a colon.
.El
.Sh EXIT STATUS
The following exit values are returned:
.Bl -tag -width Ds
.It \00
The user was successfully clocked in or out.
.It \01
The current date is configured as a skip day.
.It >1
An error occurred.
.El
