#!/bin/sh
# Copyright 2026 edcsnt. All rights reserved.

CONFIG='
01-01
01-25
04-21
05-01
07-09
09-07
10-12
11-02
11-15
11-20
12-24
12-25
12-31
2026-02-17
2026-02-18
2026-04-03
2026-06-04
'

echo() { printf %s\\n "$*"; } >&2

[ $# -eq 1 ] || { echo usage: "$0" file; exit 2; }

read -r F <"$1"
Y=$(date +%Y)
T=$(date +%Y-%m-%d)
N='
'

skip=
for d in $CONFIG
do
	case $d in
		[0-9][0-9]-[0-9][0-9]) skip=$skip$N$Y-$d ;;
		                    *) skip=$skip$N$d
	esac
done

case $skip in
	*$T*) echo "$T" is a skip day; exit 1
esac

echo clocking in/out
curl -d UserName="${F%%:*}" --data-urlencode Password="${F#*:}" \
	https://www.dimepkairos.com.br/Dimep/Account/Marcacao
