#!/bin/sh
# Copyright 2026 edcsnt. All rights reserved.

config='
01-01
01-25
04-21
05-01
07-09
09-07
10-12
11-02
11-15
11-20
12-24
12-25
12-31
2026-02-17
2026-02-18
2026-04-03
2026-06-04
'

ok() { case $1 in '') return 1 ;; *) return 0; esac; }

log() { printf %s\\n "$*"; } >&2

ckdate() {
	d=${1%%T*}
	n='
'

	case $n$config$n in
		*$n$d$n*|*$n${d#*-}$n*) log "$1" is a skip day; exit 1
	esac
}

force=
case $1 in -f) force=1; shift; esac
[ $# -eq 1 ] || { log usage: "$(basename "$0")" [-f] file; exit 2; }

dt=$(date +%Y-%m-%dT%H:%M:%S)
ok $force || ckdate "$dt"

log "$dt" clocking in/out
read -r f <"$1"
# TODO: use --out-null
printf %s "${f#*:}" \
	| curl -d UserName="${f%%:*}" --data-urlencode Password@- \
	-fo /dev/null -Ss https://www.dimepkairos.com.br/Dimep/Account/Marcacao
